<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-5BKKI8L" failures="1" tests="1" name="Default test" time="0.068" errors="0" timestamp="2024-04-25T12:41:54 IST">
  <testcase classname="com.allianz.test.Login2Test" name="invalidLoginTest" time="0.0">
    <failure type="org.testng.TestNGException" message="
Some DataProvider public java.lang.Object[][] com.allianz.utils.DataUtils.commonDataProvider(com.sun.org.apache.bcel.internal.classfile.Method) throws java.io.IOException parameters unresolved:  at 0 type class com.sun.org.apache.bcel.internal.classfile.Method
">
      <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.Object[][] com.allianz.utils.DataUtils.commonDataProvider(com.sun.org.apache.bcel.internal.classfile.Method) throws java.io.IOException parameters unresolved:  at 0 type class com.sun.org.apache.bcel.internal.classfile.Method

at org.testng.internal.invokers.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:237)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:156)
at org.testng.internal.Parameters.handleParameters(Parameters.java:812)
at org.testng.internal.Parameters.handleParameters(Parameters.java:737)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:915)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
  <testcase classname="com.allianz.test.Login2Test" name="validLoginTest" time="0.0">
    <ignored/>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- Default test -->
